name: Test
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Build
        run: swift build
      - name: Test
        run: swift test
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libsecret-1-dev
      - name: Build
        run: swift build
